version: '3.4'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
      target: basic
    volumes:
      - ./public:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    volumes:
      - ./:/var/app
      - ~/.composer:/.composer
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - "33600:3306"
    environment:
        MYSQL_DATABASE: service-core-api
        MYSQL_USER: guest
        MYSQL_PASSWORD: guest
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-db-data:/var/lib/mysql

volumes:
  mysql-db-data:
