api_controllers:
    resource: ../src/*/Entrypoint/Http/*/*Controller.php
    type: annotation
    prefix: /core/v1

status_controllers:
    resource: ../src/*/Entrypoint/Http/*Controller.php
    type: annotation
    prefix: